// packages/micro-app-utils/react18/MicroComponent.tsx
import React, { useEffect, useMemo } from 'react';
import { isSubApp, sendGlobalData } from '../index';
import { MicroComponentSlotMap } from '../data';
import { BaseObj } from '../types';

interface MicroComponentProps {
  /** 派发组件名称，注册了才能用 */
  _is: string;
  /** 其他属性 */
  [key: string]: any;
}

/**
 * 插槽统一通过属性传，不要通过children传
 */
const MicroComponent: React.FC<MicroComponentProps> = (props: BaseObj<any>) => {
  const { _is, ...otherProps } = props;

  /** 插槽，从props过滤得到 */
  const slotNameList = Object.keys(props).filter((propKey) =>
    React.isValidElement(props[propKey])
  );

  // 生成唯一的 DOM ID
  const elementId = useMemo(() => {
    return `micro_component_${('' + Date.now()).slice(5)}_${Math.random()
      .toString(36)
      .substring(2)}`;
  }, []);

  let timeoutId: NodeJS.Timeout;

  useEffect(() => {
    // 子应用使用时必须传 _is，主应用使用(插槽情况)不需要传 _id
    if (isSubApp && !_is) return;

    // 必须延迟，否则并列组件渲染只会发送的事件会被覆盖
    timeoutId = setTimeout(() => {
      if (isSubApp) {
        MicroComponentSlotMap[elementId] = slotNameList.reduce((result, slotName) => {
          result[slotName] = props[slotName];
          return result;
        }, {} as BaseObj<any>);

        sendGlobalData({
          emitName: 'micro_component',
          parameters: [
            {
              subAppName: window.__MICRO_APP_NAME__,
              componentName: _is,
              elementId,
              props: otherProps,
              slotNameList,
            },
          ],
        });
      }
    });

    return () => {
      clearTimeout(timeoutId);
    };
  }, [_is, otherProps]);

  /** 销毁钩子 */
  useEffect(() => {
    // 清除插槽缓存
    if (isSubApp && MicroComponentSlotMap[elementId]) {
      delete MicroComponentSlotMap[elementId];
    }
    setTimeout(() => {
      sendGlobalData({
        emitName: 'micro_component_destroy',
        parameters: [elementId],
      });
    });
  }, []);

  return (
    <div
      className="MicroComponent"
      id={elementId}
    >
      {props.children}
    </div>
  );
};

export default MicroComponent;

// packages/micro-app-utils/vue2/MicroComponent.vue
<template>
  <div
    class="MicroComponent"
    :id="elementId"
    v-once
  ></div>
</template>

<script>
import {
  generateMicroComponentDomId,
  isSubApp,
  sendDataDown,
  sendGlobalData,
} from '../index';
import { MicroComponentSlotMap } from '../data';

/** 每次使用生成一个唯一的dom id */
const elementId = generateMicroComponentDomId();

export default {
  name: 'MicroComponent',
  props: {
    /** 指定渲染组件名称 */
    _is: {
      type: String,
      required: true,
    },
    /** 子应用使用时候不需要传 */
    _subAppName: {
      type: String,
      default: '',
    },
    /** 子应用使用时候不需要传 */
    _slotName: {
      type: String,
      default: '',
    },
    /** 子应用使用时候不需要传 */
    _parentElementId: {
      type: String,
      default: '',
    },
  },
  data() {
    return {
      elementId,
    };
  },
  computed: {
    /** 组件名和属性值拼接的字符串 */
    componentName_props() {
      return this._is + JSON.stringify(this.$attrs);
    },
  },
  watch: {
    /** 组件名 / 剩余参数发生变化，更新数据 */
    componentName_props: {
      handler(newValue, oldValue) {
        /** 子应用使用时必须传_is，主应用使用(插槽情况)不需要传_id */
        if (isSubApp && !this._is) return;
        /** 必须延迟，否则并列组件渲染只会发送的事件会被覆盖 */
        setTimeout(() => {
          /**
           * 如果是子应用，则向主应用发送派发组件请求
           */
          if (isSubApp) {
            /** vue2要用$scopedSlots而不是$slots */
            MicroComponentSlotMap[elementId] = this.$scopedSlots;
            /**
             * vue2的props和event是分开的，且事件前缀不带on
             */
            const otherProps = this.$attrs;
            Object.keys(this.$listeners).forEach((eventKey) => {
              otherProps[`on${eventKey[0].toUpperCase()}${eventKey.slice(1)}`] =
                this.$listeners[eventKey];
            });
            sendGlobalData({
              emitName: 'micro_component',
              parameters: [
                {
                  subAppName: window.__MICRO_APP_NAME__,
                  componentName: this._is,
                  elementId,
                  props: otherProps,
                  slotNameList: Object.keys(this.$scopedSlots),
                },
              ],
            });
          } else {
            /**
             * 如果是主应用，则是插槽情况需要向子应用发送渲染插槽请求
             */
            sendDataDown(props._subAppName, {
              emitName: 'micro_component',
              parameters: [
                {
                  slotName: this._slotName,
                  elementId,
                  parentElementId: this._parentElementId,
                  props: this.$attrs,
                },
              ],
            });
          }
        });
      },
      immediate: true,
    },
  },
  beforeDestroy() {
    /** 清除插槽缓存 */
    if (isSubApp && MicroComponentSlotMap[elementId]) {
      delete MicroComponentSlotMap[elementId];
    }
    setTimeout(() => {
      sendGlobalData({
        emitName: 'micro_component_destroy',
        parameters: [elementId],
      });
    });
  },
};
</script>

<style scoped>
.MicroComponent {
  display: contents;
}
</style>
