// packages/micro-app-utils/react18/MicroComponent.tsx
import React, { useEffect, useMemo } from 'react';
import { isSubApp, sendGlobalData } from '../index';
import { MicroComponentSlotMap } from '../data';
import { BaseObj } from '../types';

interface MicroComponentProps {
  /** 派发组件名称，注册了才能用 */
  _is: string;
  /** 其他属性 */
  [key: string]: any;
}

/**
 * 插槽统一通过属性传，不要通过children传
 */
const MicroComponent: React.FC<MicroComponentProps> = (props: BaseObj<any>) => {
  const { _is, ...otherProps } = props;

  /** 插槽，从props过滤得到 */
  const slotNameList = Object.keys(props).filter((propKey) =>
    React.isValidElement(props[propKey])
  );

  // 生成唯一的 DOM ID
  const elementId = useMemo(() => {
    return `micro_component_${('' + Date.now()).slice(5)}_${Math.random()
      .toString(36)
      .substring(2)}`;
  }, []);

  let timeoutId: NodeJS.Timeout;

  useEffect(() => {
    // 子应用使用时必须传 _is，主应用使用(插槽情况)不需要传 _id
    if (isSubApp && !_is) return;

    // 必须延迟，否则并列组件渲染只会发送的事件会被覆盖
    timeoutId = setTimeout(() => {
      if (isSubApp) {
        MicroComponentSlotMap[elementId] = slotNameList.reduce((result, slotName) => {
          result[slotName] = props[slotName];
          return result;
        }, {} as BaseObj<any>);

        sendGlobalData({
          emitName: 'micro_component',
          parameters: [
            {
              subAppName: window.__MICRO_APP_NAME__,
              componentName: _is,
              elementId,
              props: otherProps,
              slotNameList,
            },
          ],
        });
      }
    });

    return () => {
      clearTimeout(timeoutId);
    };
  }, [_is, otherProps]);

  /** 销毁钩子 */
  useEffect(() => {
    // 清除插槽缓存
    if (isSubApp && MicroComponentSlotMap[elementId]) {
      delete MicroComponentSlotMap[elementId];
    }
    setTimeout(() => {
      sendGlobalData({
        emitName: 'micro_component_destroy',
        parameters: [elementId],
      });
    });
  }, []);

  return (
    <div
      className="MicroComponent"
      id={elementId}
    >
      {props.children}
    </div>
  );
};

export default MicroComponent;

// packages/micro-app-utils/vue3/MicroComponent.vue
<template>
  <div
    class="MicroComponent"
    :id="elementId"
    v-once
  ></div>
</template>

<script lang="ts" setup>
import { isSubApp, sendDataDown, sendGlobalData } from '../index';
import { MicroComponentSlotMap } from '../data';
import { MicroComponents } from '../types';
import { PropType, onUnmounted, useAttrs, useSlots, watch } from 'vue';

/**
 * 注：vue3版的MicroComponent需要考虑主应用使用的情况
 */
const props = defineProps({
  /** 指定渲染组件名称 */
  _is: {
    type: String as PropType<MicroComponents>,
    required: true,
  },
  /** 子应用使用时候不需要传 */
  _subAppName: {
    type: String,
    default: '',
  },
  /** 子应用使用时候不需要传 */
  _slotName: {
    type: String,
    default: '',
  },
  /** 子应用使用时候不需要传 */
  _parentElementId: {
    type: String,
    default: '',
  },
});

/** 剩余参数 */
const otherProps = useAttrs();

/** 插槽列表 */
const slots = useSlots();

/** 每次使用生成一个唯一的dom id */
const elementId = `micro_component_${('' + Date.now()).slice(5)}_${Math.random()
  .toString(36)
  .substring(2)}`;

watch(
  [() => props._is, () => JSON.stringify(otherProps)],
  () => {
    /** 子应用使用时必须传_is，主应用使用(插槽情况)不需要传_id */
    if (isSubApp && !props._is) return;
    /** 必须延迟，否则并列组件渲染只会发送的事件会被覆盖 */
    setTimeout(() => {
      if (isSubApp) {
        MicroComponentSlotMap[elementId] = slots;
        /**
         * 如果是子应用，则向主应用发送派发组件请求
         */
        sendGlobalData({
          emitName: 'micro_component',
          parameters: [
            {
              subAppName: window.__MICRO_APP_NAME__!,
              componentName: props._is,
              elementId,
              props: otherProps,
              slotNameList: Object.keys(slots),
            },
          ],
        });
      } else {
        /**
         * 如果是主应用，则是插槽情况需要向子应用发送渲染插槽请求
         */
        sendDataDown(props._subAppName, {
          emitName: 'micro_component',
          parameters: [
            {
              slotName: props._slotName,
              elementId,
              parentElementId: props._parentElementId,
              props: otherProps,
            },
          ],
        });
      }
    });
  },
  { immediate: true }
);

onUnmounted(() => {
  /** 清除插槽缓存 */
  if (isSubApp && MicroComponentSlotMap[elementId]) {
    delete MicroComponentSlotMap[elementId];
  }

  setTimeout(() => {
    sendGlobalData({
      emitName: 'micro_component_destroy',
      parameters: [elementId],
    });
  });
});
</script>

<style lang="scss" scoped>
.MicroComponent {
  display: contents;
}
</style>
